//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dizimistas
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Sexo { get; set; }
        public System.DateTime DataNasci { get; set; }
        public string Endereco { get; set; }
        public int Numero { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string NCartao { get; set; }
        public System.DateTime Validade { get; set; }
        public string CodSeguranca { get; set; }
        public decimal Salario { get; set; }
        public string NomeImpresso { get; set; }
        public string Bandeira { get; set; }
    
        public virtual Financeiro Financeiro { get; set; }
    }
}
