//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financeiro
    {
        public int Id { get; set; }
        public string SaldoTot { get; set; }
        public string ValorDoado { get; set; }
        public string DizimistaDoador { get; set; }
        public string IgrejaBeneficiada { get; set; }
    
        public virtual Dizimistas Dizimistas { get; set; }
        public virtual Igrejas Igrejas { get; set; }
    }
}
