//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgrejaBDContainer : DbContext
    {
        public IgrejaBDContainer()
            : base("name=IgrejaBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dizimistas> DizimistasSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Email> EmailSet { get; set; }
        public virtual DbSet<Pastores> PastoresSet { get; set; }
        public virtual DbSet<Igrejas> IgrejasSet { get; set; }
        public virtual DbSet<Cultos> CultosSet { get; set; }
        public virtual DbSet<Financeiro> FinanceiroSet { get; set; }
    }
}
