//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igrejas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Igrejas()
        {
            this.Financeiro = new HashSet<Financeiro>();
            this.Cultos = new HashSet<Cultos>();
        }
    
        public int Id { get; set; }
        public string NomeIgreja { get; set; }
        public string EnderecoIgreja { get; set; }
        public int NumeroIgreja { get; set; }
        public string BairroIgreja { get; set; }
        public string UFIgreja { get; set; }
        public string CNPJIgreja { get; set; }
        public string SiteIgreja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financeiro> Financeiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cultos> Cultos { get; set; }
    }
}
