//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pastores()
        {
            this.Cultos = new HashSet<Cultos>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string PastorCPF { get; set; }
        public string PastorSexo { get; set; }
        public System.DateTime DataNascPastor { get; set; }
        public string EnderecoPastor { get; set; }
        public int NumeroPastor { get; set; }
        public string CEPPastor { get; set; }
        public string BairroPastor { get; set; }
        public string CidadePastor { get; set; }
        public string UFPastor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cultos> Cultos { get; set; }
    }
}
